config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

app_name = 'polls'

polls/models.py
from django.db import models


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(verbose_name='date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse

from .models import Question, Choice
# Create your views here.

# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")
from django.template import loader


def index(request):
    latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
    return render(request, 'polls/index.html')


# def index(request):
#    latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
#    template = loader.get_template('polls/index.html')
#    context = {'latest_question_list': latest_question_list}
#    return HttpResponse(template.render(context, request))


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


# def detail(request, question_id):
#   try:
#        question = Question.objects.get(pk = question_id)
#   except Question.DoesNotExist:
#        raise Http404("Question does not exist")
#   return render(request, 'polls/detail.html', {'question' : question})


# def detail(request, question_id):
#     return HttpResponse("Hello, world. You're looking at question %s." % question_id)


# def results(request, question_id):
#    return HttpResponse("Hello, world. You're looking at results of question %s." % question_id)

def results(request, question_i):
    question = get_object_or_404(Question, pk = question_id)
    return render(request, 'polls/results.html', question) # 안끝남

# def vote(request, question_id):
#     return HttpResponse("Hello, world. You're voting on question %s." % question_id)


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question' : question,
            'error_message' : "You didn't select a choice."
        })
    selected_choice.votes += 1
    selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=question_id))

templates/polls/detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{Question.question_text}}</h1>
    {% if error_message %} <p><strong>{{ error_message }}</strong></p> {% endif %}
    <form action="{% url 'polls:vote' question.id %}" method="post"> {{% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type = "radio" id = "choice{{ forloop.counter}}" name = "choice" value="{{choice.id}}">
            <label for = "choice{{ forloop.counter}}">{{ choice.choice_text }}</label>
        {% endfor %}
        <input type="submit" value="Vote">
    </form>




</body>
</html>

templates/polls/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li><a href="/polls/{{question.id}}/">{{question.question_text}}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>
        no polls are available.
    </p>
    {% endif %}
</body>
</html>

templates/polls/results.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{question.question_text}}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} -- {{choice.votes}} vote {{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>
    <a href="{url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>